### ISSUE TITLE
Ac 21:25

### ISSUE THREAD

**Issue by epaphras** [anjc-prod/bibledejesuschrist.org#10]
(KJV) As touching the Gentiles which believe, we have written and concluded that they observe no such thing, save only that they keep themselves from ....
(MRT) Mais à l’égard de ceux d’entre les Gentils qui ont cru, nous en avons écrit, ayant ordonné qu’ils n’observent rien de semblable; mais seulement qu’ils s’abstiennent de ...
(BJC) A l'égard des Gentils qui ont cru, nous avons décidé et nous leur avons écrit qu'ils doivent s'abstenir des ...
(LSG) A l’égard des païens qui ont cru, nous avons décidé et nous leur avons écrit qu’ils eussent à s’abstenir des ...

la portion "ayant ordonné qu’ils n’observent rien de semblable; mais seulement" présente dans la MRT et la KJV est absente de la BJC et de la LSG.

**Comment by NicolasKAROLAK** [comment]
Corrigé.
