### ISSUE TITLE
Ga 4:24

### ISSUE THREAD

**Issue by epaphras** [anjc-prod/bibledejesuschrist.org#11]
(KJV) Which things are an allegory: for these are the two covenants; ...
(MRT) Or ces choses doivent être entendues par allégorie: car ce sont les deux alliances; ...
(BJC) Ces faits ont une valeur allégorique, car ces deux femmes sont deux alliances : ...
(LSG) Ces choses sont allégoriques; car ces femmes sont deux alliances. ...

la KJV et la MRT comportent un article défini "les" devant "alliances"; pas la BJC et la LSG

**Comment by NicolasKAROLAK** [comment]
Corrigé.
