### ISSUE TITLE
Ap 14:1

### ISSUE THREAD

**Issue by epaphras** [anjc-prod/bibledejesuschrist.org#17]
(KJV) ..... having his Father’s name written in their foreheads.
(MRT) ....  qui avaient le Nom de son Père écrit sur leurs fronts.
(BJC) ...  qui avaient son Nom et le Nom de son Père écrit sur leurs fronts. 
(LSG) ... qui avaient son nom et le nom de son Père écrits sur leurs fronts.

la BJC et la LSG ont "son nom et le nom de son Père" là où la MRT et la KJV ont "le Nom de son Père"

**Comment by NicolasKAROLAK** [comment]
Corrigé.
