### ISSUE TITLE
Ap 22:6

### ISSUE THREAD

**Issue by epaphras** [anjc-prod/bibledejesuschrist.org#19]
(KJV) ... These sayings are faithful and true: and the Lord God of the holy prophets ...
(MRT) ... ces paroles sont certaines et véritables, et le Seigneur le Dieu des saints Prophètes ...
(BJC) ... Ces paroles sont certaines et véritables ; et le Seigneur, le Dieu des esprits des prophètes ...
(LSG) ... Ces paroles sont certaines et véritables; et le Seigneur, le Dieu des esprits des prophètes ...

la MRT et la KJV ont l'adjectif "saints" devant "prophètes". pas la BJC et la LSG.

**Comment by Davidnabais7** [comment]
Bonjour Epaphras,
merci pour ces informations, nous prenons en compte ces remarques.
pouvez vous m'appeler au 06.71.13.58.44 ?
Merci

**Comment by NicolasKAROLAK** [comment]
Ça a été corrigé mais j'attends la réponse de @epaphras pour cloturer le ticket.

**Comment by epaphras** [comment]
j'ai envoyé un sms à David au n° ci-essus hier soir.

**Comment by epaphras** [comment]
j'ai fait une fause manip, et j'ai clôturé iinvolontaiement. désolé.
(j'ai envoyé un sms à David hier soir)

**Comment by NicolasKAROLAK** [comment]
@epaphras : David a demandé si tu pouvais l'appeler.

**Comment by NicolasKAROLAK** [comment]
Du coup je cloture. Merci.

**Comment by Davidnabais7** [comment]
Oui je l ai eu....mercii
Le 22 janv. 2015 13:37, "Nicolas KAROLAK" <notifications@github.com> a
écrit :
