### ISSUE TITLE
Suggestion concernant Genèse 12.1 / BJC 2015 (à l'attention du frère Shora)

### ISSUE THREAD

**Issue by epaphras** [anjc-prod/bibledejesuschrist.org#4]
Bonjour à tous, et encouragements !

Ge 12.1  :
   MRT : Or l'Eternel avait dit à Abram ....
   LSG : Or l'Eternel dit à Abram ...
   BJC 2014 : Or Yahweh dit à Abram ...
   Suggestion (BJC 2015 ?) : Or Yahweh avait dit à Abram ...

Comme l'a si bien expliqué le frère Shora lors de l'émission du lundi dernier (29 déc 2014) sur tv2vie, l'appel de Yahweh à Abram a eu lieu lorsque Abram était encore en Mésopotamie, donc avant Ge 12.1; si bien que lorsqu'on arrive en Ge 12.1 c'est un fait passé, accompli, et achevé (certes jamais mentionné auparavant dans la Bible) qui est rapporté pour introduire le départ vers Canaan (Ge 12.4)

"dit" laisse penser, contrairement à "avait dit", que c'est en Ge 12.1 (donc après la mort de Térach) que Yahweh a appelé Abram.

D'où la suggestion de retenir "avait dit" (MRT, BJC 2015 ?) au lieu "dit" (BJC 2014, LSG).

En Lui.

**Comment by NicolasKAROLAK** [comment]
Merci pour la suggestion, le changement a été fait.
