### ISSUE TITLE
Luc 12:15

### ISSUE THREAD

**Issue by epaphras** [anjc-prod/bibledejesuschrist.org#6]
(KJV)  And which of you with taking thought can add to his stature one cubit?
(MRT) Et qui est celui de vous qui par son souci puisse ajouter une coudée à sa stature?
(BJC) Qui de vous par ses inquiétudes peut ajouter une coudée à la durée de sa vie ? 
(LSG) Qui de vous par ses inquiétudes peut ajouter une coudée à la durée de sa vie ? 

le grec "pechus" a été traduit par "durée de vie" dans la BJC et la LSG, et et par "stature" dans la KJV et MRT,

"coudée" étant une mesure de longueur (et non de durée), la traduction MRT (et KJV) semble plus appropriée

qu'en pensez-vous ?

**Comment by NicolasKAROLAK** [comment]
Corrigé.
