### ISSUE TITLE
Luc 14:5

### ISSUE THREAD

**Issue by epaphras** [anjc-prod/bibledejesuschrist.org#7]
(KJ) And answered them, saying, Which of you shall have an ass or an ox fallen ...
(MRT) Puis s’adressant à eux, il leur dit: qui sera celui d’entre vous, qui ayant un âne ou un boeuf ...
(BJC) Puis s'adressant à eux, il leur dit : Lequel de vous, si son fils ou son bœuf ...
(LSG)  Puis il leur dit: Lequel de vous, si son fils ou son boeuf ...

le grec "onos" est traduit par "âne" dans la MRT et la KJV, et par "fils" dans la BJC et la LSG.

est-ce volontaire ?

**Comment by NicolasKAROLAK** [comment]
Corrigé.
