### ISSUE TITLE
Ps 139:17

### ISSUE THREAD

**Issue by epaphras** [anjc-prod/bibledejesuschrist.org#8]
(KJV) How precious also are thy thoughts unto me, O God! ....
(MRT) C’est pourquoi, ô Dieu Fort ! combien me sont précieuses les considérations .,...
(BJC) Ô Dieu ! Que tes pensées sont précieuses ! ...
(LSG) Que tes pensées, ô Dieu, me semblent impénétrables! ...

seule le BJC omet le pronom "me" avant le verbe "sont" :
KJV -> "unto me"
MRT -> "me sont"
LSG -> "me semblent"

est-ce volontaire ?

**Comment by NicolasKAROLAK** [comment]
Corrigé.
