### ISSUE TITLE
Ac 21:8

### ISSUE THREAD

**Issue by epaphras** [anjc-prod/bibledejesuschrist.org#9]
(KJV) And the next day we that were of Paul’s company departed, and came unto Caesarea ...
(MRT) Et le lendemain Paul et sa compagnie partant de là, nous vînmes à Césarée ...
(BJC) Nous partîmes le lendemain, et nous arrivâmes à Césarée. ...
(LSG) Nous partîmes le lendemain, et nous arrivâmes à Césarée. ...

dans la MRT et la KJV ont "Paul et sa compagnie", là où la BJC et la LSG ont "nous".

**Comment by NicolasKAROLAK** [comment]
Merci beaucoup pour ces observations, elles sont prises en compte, vont être examinées et des corrections faites si nécessaire.

Celle-ci est corrigée.
